import type { Metadata } from 'next';
import { Nunito } from 'next/font/google';
import Navbar from './components/navbar/Navbar';
import ClientOnly from './components/ClientOnly';

const font = Nunito({
  subsets: ['latin'],
});

export const metadata: Metadata = {
  title: 'Company Profile',
  description: 'Generated by create next app',
};

const RootLayout = ({ children }: { children: React.ReactNode }) => {
  return (
    <html lang='en'>
      <ClientOnly>
        <Navbar />
      </ClientOnly>
      <body className={font.className}>{children}</body>
    </html>
  );
};

export default RootLayout;
