import './globals.css';
import type { Metadata } from 'next';
import { Nunito } from 'next/font/google';
import Navbar from './components/navbar/Navbar';
import ClientOnly from './components/ClientOnly';
import Footer from './components/footer/Footer';
import Sidebar from './components/sidebar/Sidebar';
import FixedButton from './components/FixedButton';

const font = Nunito({
  subsets: ['latin'],
});

export const metadata: Metadata = {
  title: 'Company Profile',
  description: 'Generated by create next app',
};

const RootLayout = ({ children }: { children: React.ReactNode }) => {
  return (
    <html lang='en'>
      <body className={`${font.className} className='w-full min-h-screen box-border'`}>
        <ClientOnly>
          <Navbar />
          <Sidebar />
          <FixedButton />
        </ClientOnly>
        {children}
        <Footer />
      </body>
    </html>
  );
};

export default RootLayout;
